
package org.loopingdoge.acme.jolie.cadastre;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CadastreService", targetNamespace = "org.loopingdoge.acme.cadastre.wsdl", wsdlLocation = "file:/C:/Users/Alberto/workspace/ACME-agency/src/cadastre/cadastre.wsdl")
public class CadastreService
    extends Service
{

    private final static URL CADASTRESERVICE_WSDL_LOCATION;
    private final static WebServiceException CADASTRESERVICE_EXCEPTION;
    private final static QName CADASTRESERVICE_QNAME = new QName("org.loopingdoge.acme.cadastre.wsdl", "CadastreService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Alberto/workspace/ACME-agency/src/cadastre/cadastre.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADASTRESERVICE_WSDL_LOCATION = url;
        CADASTRESERVICE_EXCEPTION = e;
    }

    public CadastreService() {
        super(__getWsdlLocation(), CADASTRESERVICE_QNAME);
    }

    public CadastreService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CADASTRESERVICE_QNAME, features);
    }

    public CadastreService(URL wsdlLocation) {
        super(wsdlLocation, CADASTRESERVICE_QNAME);
    }

    public CadastreService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CADASTRESERVICE_QNAME, features);
    }

    public CadastreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastreService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Cadastre
     */
    @WebEndpoint(name = "CadastreServicePort")
    public Cadastre getCadastreServicePort() {
        return super.getPort(new QName("org.loopingdoge.acme.cadastre.wsdl", "CadastreServicePort"), Cadastre.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cadastre
     */
    @WebEndpoint(name = "CadastreServicePort")
    public Cadastre getCadastreServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("org.loopingdoge.acme.cadastre.wsdl", "CadastreServicePort"), Cadastre.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CADASTRESERVICE_EXCEPTION!= null) {
            throw CADASTRESERVICE_EXCEPTION;
        }
        return CADASTRESERVICE_WSDL_LOCATION;
    }

}
