
package org.loopingdoge.acme.jolie.cadastre;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cadastre", targetNamespace = "org.loopingdoge.acme.cadastre.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Cadastre {


    /**
     * 
     * @param address
     * @param coordinates
     * @param error
     */
    @WebMethod(action = "cadastrialCoordinates")
    @RequestWrapper(localName = "cadastrialCoordinates", targetNamespace = "org.loopingdoge.acme.cadastre.xsd", className = "org.loopingdoge.acme.jolie.cadastre.CadastrialCoordinates")
    @ResponseWrapper(localName = "cadastrialCoordinatesResponse", targetNamespace = "org.loopingdoge.acme.cadastre.xsd", className = "org.loopingdoge.acme.jolie.cadastre.CadastrialCoordinatesResponse")
    public void cadastrialCoordinates(
        @WebParam(name = "address", targetNamespace = "")
        String address,
        @WebParam(name = "coordinates", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Coordinate> coordinates,
        @WebParam(name = "error", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> error);

}
