
package soseng.project.wsinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BuyerWebServiceService", targetNamespace = "http://acme.loopingdoge.org/", wsdlLocation = "http://localhost:8080/acme-agency-ws-0.0.1-SNAPSHOT/BuyerWebService?wsdl")
public class BuyerWebServiceService
    extends Service
{

    private final static URL BUYERWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BUYERWEBSERVICESERVICE_EXCEPTION;
    private final static QName BUYERWEBSERVICESERVICE_QNAME = new QName("http://acme.loopingdoge.org/", "BuyerWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/acme-agency-ws-0.0.1-SNAPSHOT/BuyerWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUYERWEBSERVICESERVICE_WSDL_LOCATION = url;
        BUYERWEBSERVICESERVICE_EXCEPTION = e;
    }

    public BuyerWebServiceService() {
        super(__getWsdlLocation(), BUYERWEBSERVICESERVICE_QNAME);
    }

    public BuyerWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUYERWEBSERVICESERVICE_QNAME, features);
    }

    public BuyerWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, BUYERWEBSERVICESERVICE_QNAME);
    }

    public BuyerWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUYERWEBSERVICESERVICE_QNAME, features);
    }

    public BuyerWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BuyerWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BuyerWebService
     */
    @WebEndpoint(name = "BuyerWebServicePort")
    public BuyerWebService getBuyerWebServicePort() {
        return super.getPort(new QName("http://acme.loopingdoge.org/", "BuyerWebServicePort"), BuyerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BuyerWebService
     */
    @WebEndpoint(name = "BuyerWebServicePort")
    public BuyerWebService getBuyerWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://acme.loopingdoge.org/", "BuyerWebServicePort"), BuyerWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUYERWEBSERVICESERVICE_EXCEPTION!= null) {
            throw BUYERWEBSERVICESERVICE_EXCEPTION;
        }
        return BUYERWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
