
package soseng.project.wsinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BuyerWebService", targetNamespace = "http://acme.loopingdoge.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BuyerWebService {


    /**
     * 
     * @param replyAction
     * @return
     *     returns soseng.project.wsinterface.HouseRequestReplyMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "houseProposalReply", targetNamespace = "http://acme.loopingdoge.org/", className = "soseng.project.wsinterface.HouseProposalReply")
    @ResponseWrapper(localName = "houseProposalReplyResponse", targetNamespace = "http://acme.loopingdoge.org/", className = "soseng.project.wsinterface.HouseProposalReplyResponse")
    public HouseRequestReplyMessage houseProposalReply(
        @WebParam(name = "replyAction", targetNamespace = "")
        String replyAction);

    /**
     * 
     * @param houseProfile
     * @param buyerName
     * @return
     *     returns soseng.project.wsinterface.HouseRequestReplyMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestHouses", targetNamespace = "http://acme.loopingdoge.org/", className = "soseng.project.wsinterface.RequestHouses")
    @ResponseWrapper(localName = "requestHousesResponse", targetNamespace = "http://acme.loopingdoge.org/", className = "soseng.project.wsinterface.RequestHousesResponse")
    public HouseRequestReplyMessage requestHouses(
        @WebParam(name = "houseProfile", targetNamespace = "")
        HouseProfile houseProfile,
        @WebParam(name = "buyerName", targetNamespace = "")
        String buyerName);

}
