package soseng.project.wsinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-08-26T15:55:37.834+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "BuyerWebServiceService", 
                  wsdlLocation = "http://localhost:8080/acme-agency-ws-0.0.1-SNAPSHOT/BuyerWebService?wsdl",
                  targetNamespace = "http://acme.loopingdoge.org/") 
public class BuyerWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://acme.loopingdoge.org/", "BuyerWebServiceService");
    public final static QName BuyerWebServicePort = new QName("http://acme.loopingdoge.org/", "BuyerWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/acme-agency-ws-0.0.1-SNAPSHOT/BuyerWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BuyerWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/acme-agency-ws-0.0.1-SNAPSHOT/BuyerWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BuyerWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BuyerWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BuyerWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BuyerWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BuyerWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BuyerWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BuyerWebService
     */
    @WebEndpoint(name = "BuyerWebServicePort")
    public BuyerWebService getBuyerWebServicePort() {
        return super.getPort(BuyerWebServicePort, BuyerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BuyerWebService
     */
    @WebEndpoint(name = "BuyerWebServicePort")
    public BuyerWebService getBuyerWebServicePort(WebServiceFeature... features) {
        return super.getPort(BuyerWebServicePort, BuyerWebService.class, features);
    }

}
