
package soseng.project.wsinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SellerWebServiceService", targetNamespace = "http://acme.loopingdoge.org/", wsdlLocation = "http://localhost:8080/acme-agency-ws-0.0.1-SNAPSHOT/SellerWebService?wsdl")
public class SellerWebServiceService
    extends Service
{

    private final static URL SELLERWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SELLERWEBSERVICESERVICE_EXCEPTION;
    private final static QName SELLERWEBSERVICESERVICE_QNAME = new QName("http://acme.loopingdoge.org/", "SellerWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/acme-agency-ws-0.0.1-SNAPSHOT/SellerWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SELLERWEBSERVICESERVICE_WSDL_LOCATION = url;
        SELLERWEBSERVICESERVICE_EXCEPTION = e;
    }

    public SellerWebServiceService() {
        super(__getWsdlLocation(), SELLERWEBSERVICESERVICE_QNAME);
    }

    public SellerWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SELLERWEBSERVICESERVICE_QNAME, features);
    }

    public SellerWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SELLERWEBSERVICESERVICE_QNAME);
    }

    public SellerWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SELLERWEBSERVICESERVICE_QNAME, features);
    }

    public SellerWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SellerWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SellerWebService
     */
    @WebEndpoint(name = "SellerWebServicePort")
    public SellerWebService getSellerWebServicePort() {
        return super.getPort(new QName("http://acme.loopingdoge.org/", "SellerWebServicePort"), SellerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SellerWebService
     */
    @WebEndpoint(name = "SellerWebServicePort")
    public SellerWebService getSellerWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://acme.loopingdoge.org/", "SellerWebServicePort"), SellerWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SELLERWEBSERVICESERVICE_EXCEPTION!= null) {
            throw SELLERWEBSERVICESERVICE_EXCEPTION;
        }
        return SELLERWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
