
package soseng.project.wsinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SellerWebService", targetNamespace = "http://acme.loopingdoge.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SellerWebService {


    /**
     * 
     * @param house
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "proposeHouse", targetNamespace = "http://acme.loopingdoge.org/", className = "soseng.project.wsinterface.ProposeHouse")
    @ResponseWrapper(localName = "proposeHouseResponse", targetNamespace = "http://acme.loopingdoge.org/", className = "soseng.project.wsinterface.ProposeHouseResponse")
    public String proposeHouse(
        @WebParam(name = "house", targetNamespace = "")
        House house);

}
