
package org.loopingdoge.acme.jolie.sessionmanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientSessionServerService", targetNamespace = "org.loopingdoge.acme.jolie.sessionmanager.wsdl", wsdlLocation = "file:/home/ex/Universita/Mag_I_Anno/Ingegneria_Software_Orientata_Servizi/Progetto/ACME-agency/src/camunda-session-manager/client_session_manager.wsdl")
public class ClientSessionServerService
    extends Service
{

    private final static URL CLIENTSESSIONSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTSESSIONSERVERSERVICE_EXCEPTION;
    private final static QName CLIENTSESSIONSERVERSERVICE_QNAME = new QName("org.loopingdoge.acme.jolie.sessionmanager.wsdl", "ClientSessionServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/ex/Universita/Mag_I_Anno/Ingegneria_Software_Orientata_Servizi/Progetto/ACME-agency/src/camunda-session-manager/client_session_manager.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSESSIONSERVERSERVICE_WSDL_LOCATION = url;
        CLIENTSESSIONSERVERSERVICE_EXCEPTION = e;
    }

    public ClientSessionServerService() {
        super(__getWsdlLocation(), CLIENTSESSIONSERVERSERVICE_QNAME);
    }

    public ClientSessionServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSESSIONSERVERSERVICE_QNAME, features);
    }

    public ClientSessionServerService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSESSIONSERVERSERVICE_QNAME);
    }

    public ClientSessionServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSESSIONSERVERSERVICE_QNAME, features);
    }

    public ClientSessionServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientSessionServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientSessionServer
     */
    @WebEndpoint(name = "ClientSessionServerServicePort")
    public ClientSessionServer getClientSessionServerServicePort() {
        return super.getPort(new QName("org.loopingdoge.acme.jolie.sessionmanager.wsdl", "ClientSessionServerServicePort"), ClientSessionServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientSessionServer
     */
    @WebEndpoint(name = "ClientSessionServerServicePort")
    public ClientSessionServer getClientSessionServerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("org.loopingdoge.acme.jolie.sessionmanager.wsdl", "ClientSessionServerServicePort"), ClientSessionServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSESSIONSERVERSERVICE_EXCEPTION!= null) {
            throw CLIENTSESSIONSERVERSERVICE_EXCEPTION;
        }
        return CLIENTSESSIONSERVERSERVICE_WSDL_LOCATION;
    }

}
